### PR TITLE
fix profile header

### LINKED ISSUE #20: Profile
- src/components/user/Header.jsx
- add the circle around the picture
- change the font
- change the text to white
- image

### PR DESCRIPTION
**Pull request by menthy-wu**
image
image

### CODE REVIEW

File: src/components/dynamic/user/Dashboard.jsx [hunk 1]
```diff
@@ -21,14 +21,10 @@ const Dashboard = () => {
     <div className="h-full font-poppins flex flex-col py-4 gap-3">
       <Title title="Dashboard" />
       <Header email={user.email} name={user.name} />
-      <div className="grid grid-cols-2 h-full overflow-scroll gap-3 justify-center">
-        <div className="h-full">
-          <User user={user} setUser={setUser} edit={edit} setEdit={setEdit} />
-        </div>
+      <div className="grid grid-cols-2 h-full gap-3 justify-center">
```
Comment (shahdivyank) [inline src/components/dynamic/user/Dashboard.jsx]: the justify center isn't doing anything cause flex isn't enabled, unless it works on grid

File: src/components/dynamic/user/Header.jsx [hunk 2]
```diff
@@ -26,15 +26,17 @@ const Header = ({ horizontal = true }) => {
...
-      <Image
-        src={session.user.image}
-        width={125}
-        height={125}
-        alt="Picture of user's profile"
-        className="mr-4 rounded-full overflow-hidden"
-      />
-      <div className="align-left">
-        <p className="text-2xl font-bold mb-0">{session.user.name}</p>
+      <div className="border-[1px] border-white rounded-full p-1 w-fit mr-4">
```
Comment (shahdivyank) [inline src/components/dynamic/user/Header.jsx:29]: this can be combined cause u can apply padding on the image, make the image background white, and then add margin + border

File: src/components/dynamic/user/User.jsx [hunk 3]
```diff
@@ -33,90 +33,92 @@ const User = ({ user, setUser, edit, setEdit }) => {
...
+                      diet: {
+                        ...user.diet,
+                        [option]: !user.diet[option],
+                      },
+                    })
+                  }
+                  color="bg-hackathon-green-300"
+                />
+              ))
+            : Object.keys(user.diet).map((diet, index) => (
```
Comment (shahdivyank) [inline src/components/dynamic/user/User.jsx]: what's the purpose of this? cause db stores as array im pretty sure

File: src/components/dynamic/user/User.jsx [hunk 4]
```diff
@@ -33,90 +33,92 @@ const User = ({ user, setUser, edit, setEdit }) => {
...
+            ? DIETS.map((option, index) => (
+                <Checkbox
+                  className="w-1/2"
+                  key={index}
+                  toggle={user.diet[option]}
+                  text={option}
+                  onClick={() =>
+                    setUser({
+                      ...user,
+                      diet: {
```
Comment (shahdivyank) [inline src/components/dynamic/user/User.jsx]: why is this an object

File: src/components/dynamic/user/User.jsx (hunk 3 above)
Comment (shahdivyank) [inline src/components/dynamic/user/User.jsx]: bro isn't this supposed to be an array

**Review by shahdivyank — APPROVED** [review]
